"""list activates promo

Revision ID: 85442cd50a33
Revises: d7740fd3b45a
Create Date: 2025-04-01 01:38:53.844732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85442cd50a33'
down_revision: Union[str, None] = 'd7740fd3b45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promo_user',
    sa.Column('promo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['promo_id'], ['promocodes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('promo_id', 'user_id')
    )
    op.alter_column('keys', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('keys', 'status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_table('promo_user')
    # ### end Alembic commands ###
