"""domain struct

Revision ID: 8c449bc62923
Revises: aa2dc1c3995b
Create Date: 2025-03-13 16:26:57.089743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c449bc62923'
down_revision: Union[str, None] = 'aa2dc1c3995b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('domain', sa.String(), nullable=False))
    op.drop_constraint('servers_name_in_bot_key', 'servers', type_='unique')
    op.create_unique_constraint(None, 'servers', ['domain'])
    op.drop_column('servers', 'name_in_bot')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('name_in_bot', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'servers', type_='unique')
    op.create_unique_constraint('servers_name_in_bot_key', 'servers', ['name_in_bot'])
    op.drop_column('servers', 'domain')
    # ### end Alembic commands ###
