"""fix id

Revision ID: ba30137a07b2
Revises: 85442cd50a33
Create Date: 2025-04-26 16:08:50.756245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba30137a07b2'
down_revision: Union[str, None] = '85442cd50a33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_telegram_id_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint('users_telegram_id_key', 'users', ['telegram_id'])
    # ### end Alembic commands ###
