"""key struct

Revision ID: d7740fd3b45a
Revises: 8c449bc62923
Create Date: 2025-03-14 18:02:54.592355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7740fd3b45a'
down_revision: Union[str, None] = '8c449bc62923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('keys', 'status')
    # ### end Alembic commands ###
